### ISSUE TITLE
.NET Core 3.1 Desktop Runtime

### ISSUE THREAD

**Issue by texas2607** [SlackingVeteran/frija-dev#1]
Hi,
Under Windows 11 X64 I had to install the X64 **AND** X86 version of .NET in order for Frija v2.0.21302.1 to work.
With only the X64 it does not work.

Thks

**Comment by SlackingVeteran** [comment]
Are you talking about Frija 2.x beta? or Frija 1.x. If it is 2.x then its a well known issue of .net Core and there is nothing I can do about it. if executable is targeted towards x86 than .net core >= 3.1 x86 is required. I even tested with .net 6 beta and its still same issue. They entirely removed AnyCPU executable which used to run as x86 on x86 hardware or as x64 on x64 hardware. But that is no longer possible

**Comment by texas2607** [comment]
Hi,
Thanks for your answer.
Concerning the .Net problem, maybe we should tell the users to install both (X86 and X64) at the first launch of Frija 2.x

On the other hand I have a friend under Windows 10 and in spite of the installation of the framework in X86 and X64 it always asks him for the installation at each starting of Frija 2.x

**Comment by SlackingVeteran** [comment]
Have him open a command prompt in same directory as Frija executable and
type:
`set COREHOST_TRACE=1`
`set COREHOST_TRACEFILE=t.txt`
`Frija.exe`

Those are 3 separate commands. First 2 are setting variable required for
.net core to create log file on whats going on behind the scene. Third one
starts frija from command prompt with the defined variables. Once it fails
to start or prompts to install .net core he can close the app and send the
log file for me to analyze.

**Comment by texas2607** [comment]
Thanks,
I just sent him the message.
I'll get back to you as soon as possible

**Comment by texas2607** [comment]
Hi
Commands are not recognized.

![Capture d’écran 2021-11-09 184831](https://user-images.githubusercontent.com/28494443/140977401-6a4627d0-c195-4373-a4b7-bcb63edd15be.png)

Fred

**Comment by SlackingVeteran** [comment]
Those commands were for command prompt and not powershell

**Comment by texas2607** [comment]
Same
![Capture d’écran 2021-11-09 194809](https://user-images.githubusercontent.com/28494443/140985896-f563544b-e326-461a-9c67-2d3e9e6b92e9.png)

**Comment by SlackingVeteran** [comment]
Try adding set infront of those commands:
set COREHOST_TRACE=1

**Comment by texas2607** [comment]
Tracing enabled @ Tue Nov  9 19:22:28 2021 GMT
--- Invoked apphost [version: 3.1.19, commit hash: aae002469c4fe298a532e11faa01378048840aa9] main = {
frija.exe
}
Redirecting errors to custom writer.
The managed DLL bound to this executable is: 'Frija.dll'
Files embedded within the bundled will be extracted to [D:\Fichiers Temporaires\tmp\.net\Frija\4rdyshxi.ojr] directory
Can't get the size of the SDK location registry value or it's empty, result: 0x2
Using global installation location [C:\Program Files (x86)\dotnet] as runtime location.
Reading fx resolver directory=[C:\Program Files (x86)\dotnet\host\fxr]
Considering fxr version=[3.1.20]...
Considering fxr version=[5.0.4]...
Detected latest fxr version=[C:\Program Files (x86)\dotnet\host\fxr\5.0.4]...
A fatal error occurred, the required library

**Comment by SlackingVeteran** [comment]
That’s incomplete. Can i get the entire file?

**Comment by texas2607** [comment]
Hi
Sorry

"Tracing enabled @ Tue Nov  9 19:22:28 2021 GMT
--- Invoked apphost [version: 3.1.19, commit hash: aae002469c4fe298a532e11faa01378048840aa9] main = {
frija.exe
}
Redirecting errors to custom writer.
The managed DLL bound to this executable is: 'Frija.dll'
Files embedded within the bundled will be extracted to [D:\Fichiers Temporaires\tmp\.net\Frija\4rdyshxi.ojr] directory
Can't get the size of the SDK location registry value or it's empty, result: 0x2
Using global installation location [C:\Program Files (x86)\dotnet] as runtime location.
Reading fx resolver directory=[C:\Program Files (x86)\dotnet\host\fxr]
Considering fxr version=[3.1.20]...
Considering fxr version=[5.0.4]...
Detected latest fxr version=[C:\Program Files (x86)\dotnet\host\fxr\5.0.4]...
A fatal error occurred, the required library hostfxr.dll could not be found in [C:\Program Files (x86)\dotnet\host\fxr\5.0.4]"

**Comment by SlackingVeteran** [comment]
There is definitely some kind of issue with .net core installation on his PC. Have him make sure .net is installed properly in the directory that log file is looking for.

From what I can tell, he has modified some stuffs on his system as to where things are stored. For example temporary files, probably same is right for .net installation. Its preferred to install framework on default directories unless you know what you are doing and know how to fix issues.

Frija has nothing to do with the issue mentioned in the logs. It is the user’s system itself.

**Comment by texas2607** [comment]
The problem seems to be solved after reinstalling the SDK/.Net core configuration files and the framework
Thanks a lot

Fred
