### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by texas2607** [SlackingVeteran/frija-dev#2]
Hi,
If I check "binary nature" in the options, the next time I launch Frija it is unchecked.
Is it possible to make Frija keep the selected options?

Thanks
Fred

**Comment by SlackingVeteran** [comment]
Are other settings saving just fine but not binary nature?

**Comment by texas2607** [comment]
Hi
So if I check :
- Binary nature only -> Next launch not checked
- CRC Check only -> Next launch I have Binary Nature + CRC Check checked
- CRC Check + Binary Nature -> Next launch both are checked

Fred

**Comment by SlackingVeteran** [comment]
Alright, i will look into it

**Comment by texas2607** [comment]
Hi
Otherwise maybe it would be possible to put these 2 "options" directly on the main window of Frija (under CRC for example) because depending on the case we need the Binary Nature (or not) and having the checkbox directly without going through "Settings" would be easier
And we could see directly which option is checked

Fred

**Comment by SlackingVeteran** [comment]
I finally got some free time to look into the issue and noticed it has already been fixed since 1st beta release.
It was just some tests I was running which I forgot to revert before beta release
