### ISSUE TITLE
App not starting

### ISSUE THREAD

**Issue by caniculabv** [SlackingVeteran/frija-dev#3]
[Frija.log](https://github.com/SlackingVeteran/frija-dev/files/7735533/Frija.log)

**Comment by Ushie** [comment]
Can you please try installing the latest .NET Core 3.1 x86 package?
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-3.1.416-windows-x86-installer

**Comment by SlackingVeteran** [comment]
Please install x86 version of .net core 3.1
