### ISSUE TITLE
Error "To run this application, you must install .Net Core" stop running of app

### ISSUE THREAD

**Issue by SwiftExtender** [SlackingVeteran/frija-dev#8]
Error "To run this application, you must install .Net Core" stop running of app

![изображение](https://github.com/SlackingVeteran/frija-dev/assets/69252550/4c0e58af-77f1-490a-a09d-69d962558fa3)

What version of .Net Core is needed for app?

**Comment by Ushie** [comment]
.NET Core 3.1 x86

**Comment by SwiftExtender** [comment]
Thanks
